"""
Configuration - environment variable management and validation.

All configuration is loaded from environment variables (via .env file).
Only DEEPGRAM_API_KEY is required. Everything else has sensible defaults
or is optional depending on your setup:

  Local dev:    Just DEEPGRAM_API_KEY (use make_call.py with a tunnel)
  Telephony:    + SERVER_EXTERNAL_URL, TWILIO_*, ENDPOINT_SECRET
  Production:   Same as telephony, deployed behind a real domain
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# The web app owns local credentials.  Loading it here keeps the call bridge
# separate while avoiding a second copied secrets file.
_SERVICE_DIR = Path(__file__).resolve().parent
load_dotenv(_SERVICE_DIR.parent / "frontend" / ".env.local")
load_dotenv(_SERVICE_DIR / ".env", override=True)

# ---------------------------------------------------------------------------
# Required
# ---------------------------------------------------------------------------
DEEPGRAM_API_KEY = os.getenv("DEEPGRAM_API_KEY")

# ---------------------------------------------------------------------------
# Server
# ---------------------------------------------------------------------------
SERVER_HOST = os.getenv("SERVER_HOST", "0.0.0.0")
SERVER_PORT = int(os.getenv("SERVER_PORT", "8080"))

# Public URL where Twilio can reach this server (e.g. https://xxxx.ngrok.io
# or https://your-app.fly.dev).  Required for placing outbound calls -
# Twilio needs to open a WebSocket back to the server for audio streaming.
# Set automatically by setup.py, or manually for tunnel-based workflows.
SERVER_EXTERNAL_URL = os.getenv("SERVER_EXTERNAL_URL")

# ---------------------------------------------------------------------------
# Voice Agent
# ---------------------------------------------------------------------------
VOICE_MODEL = os.getenv("VOICE_MODEL", "aura-2-thalia-en")
TTS_PROVIDER = os.getenv("TTS_PROVIDER", "deepgram")
LLM_MODEL = os.getenv("LLM_MODEL", "gpt-4o-mini")
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "open_ai")

# ---------------------------------------------------------------------------
# Twilio (required for placing outbound calls)
# ---------------------------------------------------------------------------
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER")

# ---------------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------------
# Endpoint secret for authenticating POST /make-call requests.
# Generated by setup.py or set manually.
ENDPOINT_SECRET = os.getenv("ENDPOINT_SECRET")

# The Next.js server proxies browser requests to this service using this
# secret.  Set it to a random value before a demo; do not put it in browser
# code.  The service remains usable locally without it for initial setup.
FRONTEND_ORIGIN = os.getenv("FRONTEND_ORIGIN", "http://127.0.0.1:3002")

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------
if not DEEPGRAM_API_KEY:
    raise ValueError(
        "Missing required environment variable: DEEPGRAM_API_KEY\n"
        "Get a free key at https://console.deepgram.com"
    )
